const pigFacts = [
    "Pigs are considered one of the most intelligent domesticated animals, often compared to dogs and even primates in cognitive ability.",
    "Pigs can't sweat because they have very few sweat glands. That's why they roll in mud to cool off!",
    "A pig's squeal can be as loud as 115 decibels - that's louder than a jet engine at takeoff!",
    "Pigs have an excellent sense of smell and are used to find truffles, a highly prized culinary ingredient.",
    "Newborn piglets learn to run to their mothers' voices, and mother pigs sing to their babies while nursing.",
    "Pigs can run at speeds up to 11 miles per hour - that's faster than a 6-minute mile!",
    "Pigs have excellent long-term memories and can remember things they learned years earlier.",
    "A pig's tongue contains 15,000 taste buds. Humans have only about 9,000.",
    "Pigs dream just like humans do. Scientists have observed REM sleep in pigs.",
    "Pigs are very social animals and form close bonds with each other. They love to sleep nose-to-nose.",
    "Pigs can play video games! Studies have shown they can learn to use joysticks with their snouts.",
    "A pig's snout is a highly sensitive organ used for digging and finding food underground.",
    "Pigs are naturally very clean animals and will designate a bathroom area away from where they eat and sleep.",
    "Wild pigs can be found on every continent except Antarctica.",
    "Pigs can recognize themselves in mirrors, a sign of self-awareness that few animals possess.",
    "A group of pigs is called a sounder, a drift, or a drove.",
    "Pigs have been trained to detect landmines and help with search and rescue operations.",
    "Pigs communicate with over 20 different vocalizations, from grunts to squeals.",
    "A pig's heart is so similar to a human heart that pig heart valves are used in human heart surgery.",
    "Pigs have panoramic vision of about 310 degrees and can see behind themselves without turning their heads.",
    "Pigs love music and have been shown to prefer certain genres over others.",
    "The phrase 'sweating like a pig' is a misnomer since pigs can hardly sweat at all!",
    "Pigs are one of the oldest domesticated animals, first domesticated around 9,000 years ago.",
    "A mother pig is called a sow, a father pig is called a boar, and babies are called piglets.",
    "Pigs can hold their breath for up to 5 minutes when swimming.",
    "Winston Churchill famously said: 'Dogs look up to us. Cats look down on us. Pigs treat us as equals.'",
    "Pigs have four toes on each foot but only walk on two of them.",
    "The average pig sleeps about 8 hours a day, similar to humans.",
    "Pigs can learn their names within the first two weeks of life.",
    "A pig's sense of smell is about 2,000 times more sensitive than a human's.",
    "Pigs have been shown to have empathy and can sense when other pigs are happy or upset.",
    "A pig's gestation period is 3 months, 3 weeks, and 3 days.",
    "Pigs were domesticated in China around 7500 BC.",
    "The smallest breed of pig is the Kunekune, which originated in New Zealand.",
    "Pigs can swim! They're actually excellent swimmers and some wild pigs swim between islands.",
    "A pig named Hamlet was the first pig to be trained as a service animal.",
    "Pigs are used in medical research because their organs are similar in size and function to human organs.",
    "The largest pig ever recorded weighed 2,552 pounds and was named Big Bill.",
    "Pigs can learn tricks faster than dogs in many cases.",
    "Baby pigs (piglets) can recognize their own names by the time they're 2 weeks old.",
    "Pigs have been shown to understand the concept of reflection at a younger age than human children.",
    "A pig's memory is so good they can remember specific locations of food for years.",
    "Pigs use different grunts to communicate different things, like a special grunt for food.",
    "The curly tail of a pig is actually a sign of good health - stressed pigs have straight tails.",
    "Pigs can feel optimism and pessimism, just like humans.",
    "In Denmark, there are twice as many pigs as people.",
    "Pigs are the 4th most intelligent animal on Earth, after chimpanzees, dolphins, and elephants.",
    "Ancient Egyptians considered pigs sacred to the god Set.",
    "A pig's skin is very similar to human skin and is sometimes used for treating burn victims.",
    "Pigs can distinguish between pigs they know and pigs that are strangers.",
    "The word 'piggyback' comes from 'pick pack' and has nothing to do with pigs.",
    "Pigs can be house-trained just like dogs and cats.",
    "Wild boars can run up to 30 miles per hour when threatened.",
    "Pigs have been used to pull carts and plows throughout history.",
    "The pig is the 12th animal in the Chinese zodiac.",
    "Pigs roll in mud to protect their skin from sunburn and parasites.",
    "A pig's sense of direction is excellent - they rarely get lost.",
    "Pigs are omnivores and will eat almost anything, including vegetables, fruits, and insects.",
    "The world's oldest pig lived to be 23 years old.",
    "Pigs greet each other by rubbing noses.",
    "A pig's teeth never stop growing throughout their lifetime.",
    "Pigs can be taught to fetch, sit, and spin just like dogs.",
    "In the Bahamas, there's a beach where wild pigs swim in the ocean and greet tourists.",
    "Pigs have been known to save their owners' lives by alerting them to dangers.",
    "A pig named Lulu saved her owner's life by lying in traffic to stop cars and get help.",
    "Pigs can become depressed if they don't have enough mental stimulation.",
    "The Vietnamese Pot-bellied pig became a popular pet in the 1980s.",
    "Pigs are farmed on every continent except Antarctica.",
    "A pig can eat 4-6 pounds of food per day.",
    "Pigs prefer to sleep with their heads pointing north or south, aligned with Earth's magnetic field.",
    "The bristles on a pig's back stand up when they're excited or scared.",
    "Pigs can recognize up to 30 individual pigs in their social group.",
    "A pig's snout can move independently of its head to root around in soil.",
    "Pigs have been trained to sniff out drugs and explosives, like dogs.",
    "The phrase 'pig-headed' refers to the stubbornness pigs can show when they don't want to do something.",
    "Pigs need companionship and do poorly when kept alone.",
    "A pig's average body temperature is 102.5°F (39.2°C).",
    "Pigs were brought to the Americas by Christopher Columbus in 1493.",
    "The red wattle pig is known for the fleshy wattles that hang from its neck.",
    "Pigs can be trained to come when called, just like dogs.",
    "A group of young pigs playing together is called a 'litter at play.'",
    "Pigs have been living alongside humans for over 10,000 years.",
    "The Gloucestershire Old Spots pig is known for its excellent mothering abilities.",
    "Pigs can suffer from the same diseases as humans, including the flu.",
    "A pig uses its snout like a hand to explore and manipulate objects.",
    "Pigs have been shown to anticipate future events and plan accordingly.",
    "The Mangalitsa pig has a woolly coat that looks like sheep's wool.",
    "Pigs produce 20 million tons of manure per year in the United States alone.",
    "A pig's intelligence has been compared to that of a 3-year-old human child.",
    "Pigs are curious animals and love to explore new environments.",
    "The Hampshire pig is one of the oldest American breeds of pig.",
    "Pigs can sense time and know when it's feeding time.",
    "A baby pig doubles its birth weight in the first week of life.",
    "Pigs form hierarchies in their social groups with dominant and submissive members.",
    "The Berkshire pig is known for producing high-quality pork in Japan.",
    "Pigs can be trained to use a litter box indoors.",
    "A pig's eyesight is not as good as its other senses, but they can see in color.",
    "Pigs have been known to console other distressed pigs by staying close to them.",
    "The Tamworth pig is one of the oldest pig breeds, originating in England.",
    "Pigs can learn to open gates and doors to escape enclosures.",
    "A sow can have 8-12 piglets in a single litter.",
    "Pigs have been used in therapy settings to help people with disabilities.",
    "The Pietrain pig has distinctive black spots and is known for its muscular body.",
    "Pigs can travel up to 30 miles in a single day when foraging.",
    "A pig's nose print is unique, just like a human fingerprint.",
    "Pigs have been shown to prefer novelty and get bored with the same routine.",
    "The Duroc pig is known for its reddish-brown color and fast growth rate.",
    "Pigs can suffer from loneliness and depression when separated from their companions.",
    "A pig's hearing is much more sensitive than a human's.",
    "Pigs in ancient Rome were used to clear land by rooting up vegetation.",
    "The Large Black pig is known for being docile and a good forager.",
    "Pigs have been selectively bred for over 300 generations.",
    "A pig can produce about 8 piglets per litter on average.",
    "Pigs are crepuscular, meaning they're most active at dawn and dusk.",
    "The Poland China pig was developed in Ohio in the 1800s.",
    "Pigs can recognize human faces and remember people who have treated them well or poorly.",
    "A pig's tail wags when it's happy, similar to a dog.",
    "Pigs in medieval Europe were often allowed to roam the streets freely.",
    "The Chester White pig originated in Chester County, Pennsylvania.",
    "Pigs have been shown to use tools in laboratory settings.",
    "A pig's sense of touch in its snout is incredibly refined.",
    "Pigs were considered sacred in ancient Celtic cultures.",
    "The Landrace pig is known for its long body and excellent milk production.",
    "Pigs can remember the solution to a puzzle for at least 3 years.",
    "A pig's ear is sometimes used as a chew treat for dogs.",
    "Pigs have been painted by famous artists throughout history.",
    "The Spotted pig is known for its distinctive black and white markings.",
    "Pigs can form friendships that last their entire lives.",
    "A pig's nose has a special disk of cartilage that helps it dig.",
    "Pigs in ancient Greece were sacrificed to the goddess Demeter.",
    "The Yorkshire pig is one of the most common breeds worldwide.",
    "Pigs have been shown to understand symbolic language to some degree.",
    "A pig's stomach has a simple structure similar to a human's.",
    "Pigs were among the first animals to be cloned successfully.",
    "The Oxford Sandy and Black pig nearly went extinct in the 1980s.",
    "Pigs can learn from watching other pigs complete tasks.",
    "A pig's liver has been used for human liver transplants in experimental procedures.",
    "Pigs in Japan are sometimes kept as pets and walked on leashes.",
    "The Meishan pig from China can have up to 20 piglets in a single litter.",
    "Pigs have been trained to herd sheep, just like border collies.",
    "A pig's brain is about the size of a tangerine.",
    "Pigs were used as mine detectors in Croatia after the Yugoslav Wars.",
    "The American Guinea Hog is a small heritage breed perfect for small farms.",
    "Pigs can distinguish between classical music and rock music.",
    "A sow is pregnant for about 114 days before giving birth.",
    "Pigs have been featured as main characters in many famous books and movies.",
    "The British Lop pig is one of the rarest pig breeds in the world.",
    "Pigs can navigate mazes as well as or better than dogs.",
    "A pig's insulin was used to treat diabetes before synthetic insulin was developed.",
    "Pigs in the wild create nests for their babies using grass and leaves.",
    "The Hereford pig has distinctive red and white coloring like Hereford cattle.",
    "Pigs have complex social lives with friends, rivals, and family bonds.",
    "A pig farmer is sometimes called a 'swineherd.'",
    "Pigs can understand basic commands in multiple languages.",
    "The Middle White pig is known for its upturned snout.",
    "Pigs have been shown to have individual personalities.",
    "A wild boar's tusks can grow up to 6 inches long.",
    "Pigs were used to find underground water sources in some cultures.",
    "The Saddleback pig has a distinctive white band around its shoulders.",
    "Pigs can experience positive emotions like joy and contentment.",
    "A pig's lifespan in the wild can be up to 20 years.",
    "Pigs have been bred in virtually every color imaginable.",
    "The Iron Age Pig is a rare breed developed to resemble ancient wild boars.",
    "Pigs can understand cause and effect relationships.",
    "A piglet weighs about 2.5 pounds at birth.",
    "Pigs were once used to stamp out fires in fire brigades.",
    "The Kune Kune pig is known for being especially friendly to humans.",
    "Pigs have been documented using deception to mislead other pigs to food sources.",
    "A pig can drink up to 14 gallons of water per day.",
    "Pigs in ancient Polynesia were considered a form of currency.",
    "The Red Wattle pig nearly went extinct but was saved by conservation efforts.",
    "Pigs can tell the difference between a kind handler and a rough one.",
    "A pig's squeal is its way of expressing various emotions.",
    "Pigs have been trained to act in movies and television shows.",
    "The Ossabaw Island pig has adapted to survive on very little food.",
    "Pigs can problem-solve and figure out how to access food rewards.",
    "A pig's fat (lard) was traditionally used for cooking and making soap.",
    "Pigs were once used to pull milk carts in Belgium.",
    "The Mora Romagnola pig from Italy has ancient Roman origins.",
    "Pigs can sense the emotional state of humans around them.",
    "A fully grown domestic pig can weigh between 300-700 pounds.",
    "Pigs have been shown to prefer certain types of bedding for comfort.",
    "The Mulefoot pig is known for its solid, non-cloven hooves.",
    "Pigs can be potty trained in as little as a few days.",
    "A pig's digestive system is remarkably similar to a human's.",
    "Pigs in medieval times were often accused of crimes and put on trial.",
    "The Lincolnshire Curly Coat pig went extinct in 1972.",
    "Pigs can adjust their behavior based on what they've learned from past experiences.",
    "A sow can recognize her piglets even after they've been separated for months.",
    "Pigs have been used in scientific research to study human diseases.",
    "The Choctaw pig is a rare American heritage breed.",
    "Pigs can sense changes in barometric pressure and may act differently before storms.",
    "A pig's hooves are similar in structure to human fingernails.",
    "Pigs were once common in New York City, roaming the streets until the 1800s."
];

// Local pig images
const pigImages = [
    "images/7bf3ea20aae062fb4ff9d3f1b7577c08.jpg",
    "images/amber-kipp-EwJMBIshgXU-unsplash.jpg",
    "images/christopher-carson-i4XLJmlYit4-unsplash.jpg",
    "images/close-up-of-a-baby-pig-683817525-5c8ba9d846e0fb0001555818.webp",
    "images/close-up-of-pig-702612173-5c8ba81146e0fb00016ee068.webp",
    "images/Cute-Pigs.jpg",
    "images/dan-renco-Y06imaOLycY-unsplash.jpg",
    "images/diego-san-tlJ_5jVHMF4-unsplash.jpg",
    "images/five-piglets-157339366-5c8baefb46e0fb00016ee06b.webp",
    "images/forest-s-ZKbve9f7Mp4-unsplash.jpg",
    "images/front-view-closeup-of-black-and-white-spotted-piglet-on-hay-on-a-sunny-day-881477548-5c8ba7b746e0fb000187a286.webp",
    "images/GettyImages-1056409580.jpg",
    "images/GettyImages-1091845028.jpg",
    "images/GettyImages-1150300620.jpg",
    "images/GettyImages-1178210573-e1614982597559.jpg",
    "images/GettyImages-1196949553.jpg",
    "images/GettyImages-1202231579.jpg",
    "images/GettyImages-1263051087.jpg",
    "images/GettyImages-1273972629.jpg",
    "images/GettyImages-129291044-scaled.jpg",
    "images/GettyImages-129369839-scaled-e1614982709753.jpg",
    "images/GettyImages-130871377.jpg",
    "images/GettyImages-142769905.jpg",
    "images/GettyImages-157339366-scaled.jpg",
    "images/GettyImages-160499148.jpg",
    "images/GettyImages-170617892-scaled-e1614980455872.jpg",
    "images/GettyImages-465857056-scaled.jpg",
    "images/GettyImages-499164441.jpg",
    "images/GettyImages-558238457-scaled-e1614983275759.jpg",
    "images/GettyImages-578260696-scaled.jpg",
    "images/GettyImages-654512248.jpg",
    "images/GettyImages-658787292-scaled-e1614980627142.jpg",
    "images/GettyImages-667206-001.jpg",
    "images/GettyImages-71919568.jpg",
    "images/GettyImages-71951027.jpg",
    "images/GettyImages-769707819-e1614977682258.jpg",
    "images/GettyImages-77746623.jpg",
    "images/GettyImages-78722394.jpg",
    "images/GettyImages-823610698.jpg",
    "images/GettyImages-86079146.jpg",
    "images/GettyImages-90686590-scaled-e1614975780232.jpg",
    "images/GettyImages-970942346.jpg",
    "images/GettyImages-974941486-scaled.jpg",
    "images/GettyImages-988240540-e1614978384672.jpg",
    "images/GettyImages-989386996-e1614982532849.jpg",
    "images/jonathan-cooper-Z3Z7Kp3mHtI-unsplash.jpg",
    "images/kenneth-schipper-6y7jACxmhP8-unsplash.jpg",
    "images/kenneth-schipper-Cm11a9jSKZc-unsplash.jpg",
    "images/kimberly-lake-VBmRbvMrb7A-unsplash.jpg",
    "images/laura-anderson-CP9GGy_LkIY-unsplash.jpg",
    "images/little-piggy-987544824-5c8ba8b7c9e77c00014a9d22.webp",
    "images/lucia-macedo-4gyYf1ItdHI-unsplash.jpg",
    "images/marek-piwnicki-PUVVsYJPh78-unsplash.jpg",
    "images/mathias-grischott-nG_Y_TG3O-w-unsplash.jpg",
    "images/matthieu-petiard-SSjGNxxqD6k-unsplash.jpg",
    "images/mother-pig-watching-piglets-654510950-5c8baeeec9e77c00010e966a.webp",
    "images/nico-castez-YKAJ2kQpqQw-unsplash.jpg",
    "images/pascal-debrunner-b-zyMn_e_R4-unsplash.jpg",
    "images/pig1.jpg",
    "images/pig2.jpg",
    "images/piglet-56158469-5c8ba7dc46e0fb0001770031.webp",
    "images/piglets-in-field-103576621-5c8bae8c46e0fb00014a96a1.webp",
    "images/pigs-fighting-over-carrot-846514438-5c8baa7946e0fb000146ace2.webp",
    "images/pigs-in-farm-688935901-5c8ba7fac9e77c0001ac181c.webp",
    "images/samuel-cruz-LlGGul6E_KM-unsplash.jpg",
    "images/ShortStack-264650932_Courtesy-Mary-Maag-scaled.jpg",
    "images/stefanie-poepken-9tSzeU5ZSLQ-unsplash.jpg",
    "images/the-pig-race-is-on-871564996-5c8bae50c9e77c0001ac1820.webp",
    "images/two-long-haired-pigs-grazing-in-a-pasture-520241423-5c8bae12c9e77c0001ac1820.webp",
    "images/two-piglets-leaning-e1614980898255.jpg",
    "images/two-pigs-swimming-in-the-bahamas-507961772-5c8baf5346e0fb000146ace4.webp",
    "images/veronica-white-ZuixmDWAHq8-unsplash.jpg",
    "images/young-piglet-looking-over-e1614985236196.jpg",
    "images/zoe-richardson-vMjrs3C50d8-unsplash.jpg"
];

function getDayOfYear() {
    const now = new Date();
    const start = new Date(now.getFullYear(), 0, 0);
    const diff = now - start;
    const oneDay = 1000 * 60 * 60 * 24;
    return Math.floor(diff / oneDay);
}

function formatDate() {
    const options = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };
    return new Date().toLocaleDateString('en-US', options);
}

// Simple seeded random number generator for consistent daily selections
function seededRandom(seed) {
    const x = Math.sin(seed) * 10000;
    return x - Math.floor(x);
}

function initializePage() {
    const dayOfYear = getDayOfYear();
    const year = new Date().getFullYear();
    const seed = year * 1000 + dayOfYear;

    // Set the date
    document.getElementById('date').textContent = formatDate();

    // Select pig image using seeded random
    const imageIndex = Math.floor(seededRandom(seed) * pigImages.length);
    document.getElementById('pig-image').src = pigImages[imageIndex];

    // Select pig fact using seeded random
    const factIndex = Math.floor(seededRandom(seed) * pigFacts.length);
    document.getElementById('pig-fact').textContent = pigFacts[factIndex];
}

// Initialize when the page loads
document.addEventListener('DOMContentLoaded', initializePage);
